config/routes.rb
Chat::Application.routes.draw do
 
 
 root :to => "spots#index"

 resources :spots
 resources :users do
 resources :messages
   
 end
resources :messages
 match '/userMessage/:id' =>"messages#userMessage"
 match '/privateMessages' =>"messages#privateMessages"


 resource :session
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"  
end

app/models/message.rb
class Message < ActiveRecord::Base
	
	belongs_to :user


        default_scope order('created_at DESC')
        
        default_scope where('created_at>= '+Time.now.to_s[0..9])

end

app/models/spot.rb
class Spot < ActiveRecord::Base
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  
  has_many :messages
	

  attr_accessor :password
  
  validates :email, :uniqueness => true, 
                    :length => { :within => 5..50 }, 
                    :format => { :with => /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i }
  validates :password, :confirmation => true,
                       :length => { :within => 4..20 },
                       :presence => true,
                       :if => :password_required?

 
  before_save :encrypt_new_password

  def self.authenticate(email, password)
    user = find_by_email(email)
    return user if user && user.authenticated?(password)
  end

  def authenticated?(password)
    self.hashed_password == encrypt(password)
  end

  protected
    def encrypt_new_password
      return if password.blank?
      self.hashed_password = encrypt(password)
    end

    def password_required?
      hashed_password.blank? || password.present?
    end

    def encrypt(string)
      Digest::SHA1.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected 
    # Returns the currently logged in user or nil if there isn't one
 
    def current_user
      return unless session[:user_id]
      @current_user ||= User.find_by_id(session[:user_id]) 
    end

    # Make current_user available in templates as a helper
    helper_method :current_user

    # Filter method to enforce a login requirement
    # Apply as a before_filter on any controller you want to protect
    def authenticate
      logged_in? ? true : access_denied
    end

    # Predicate method to test for a logged in user    
    def logged_in?
      current_user.is_a? User
    end

    # Make logged_in? available in templates as a helper
    helper_method :logged_in?

    def access_denied
      redirect_to login_path, :notice => "Please log in to continue" and return false
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

before_filter :authenticate 
before_filter :load_user


def index
  @messages=Message.where('receiver_id IS null')
  
  @message=Message.new
end 

def userMessage
  @messages=Message.all
  @message=Message.new
end

def privateMessages
 @private_messages=Message.where('receiver_id= :rec', :rec=>current_user.id)
end

 def create
      @message=Message.new(params[:message])
      @message.save
 if session['saved_location']=="Messages" then
     redirect_to '/messages'
    else 
      redirect_to '/userMessage/'+session['userMessageParam']
    end


end
 

 private 
  def load_user
   if params[:user_id]!=nil then
    @user= User.find(params[:user_id])
   end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now[:alert] = "Invalid login/password combination"
      render :action => 'new'
    end
  end

  def destroy
    if current_user != nil then
        prespot = Spot.find_by_sessionid(current_user.id)
        if prespot != nil then
            prespot.sessionid = nil
            prespot.save
        end
     end
     reset_session
     redirect_to(root_path)
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController 
  
  before_filter :authenticate, :only => :show 
  	
  def index
      @spots = Spot.all
  end

  def show

      if params[:id] != nil then
         busyspot = Spot.find(params[:id]).sessionid
         if busyspot == nil then
              prespot = Spot.find_by_sessionid(current_user.id)
              if prespot != nil then
                  prespot.sessionid = nil
                  prespot.save
              end
              spot = Spot.find(params[:id])
              spot.sessionid = current_user.id
              spot.save     
          
          end
      end
       redirect_to(root_path)
  end

   

end
   

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
before_filter :authenticate, :except => [:new, :create]
 # GET /users

  # GET /users.xml

  def index

    if current_user!=nil
       @users = current_user.id


       respond_to do |format|

          format.html # index.html.erb

          format.xml  { render :xml => @users }

       end

    else  redirect_to("/spots")
    end
 end




  # GET /users/1
  # GET /users/1.xml

  def show

    @user = User.find(params[:id])


    respond_to do |format|

      format.html # show.html.erb

      format.xml  { render :xml => @user }

    end

  end

 

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to users_path, :notice => 'User successfully added.'
    else
      render :action => 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    respond_to do |format|

      if @user.update_attributes(params[:user])

        format.html { redirect_to(root_path, :notice => 'Your profile was successfully updated.') }

        format.xml  { head :ok }

      else

        format.html { render :action => "edit" }

        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }

      end
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"><head>

<head>

  <title>Chat</title>

  <%= stylesheet_link_tag :all %>

  <%= javascript_include_tag :defaults %>

  <%= csrf_meta_tag %>

</head>

<body>


<div Style="float: right; border: 2px solid Black;">
<% if logged_in? %>
        <%= link_to "Logout", logout_path %><br /> 
        <a href="/users/<%=current_user.id  %>/edit">Edit your profile</a>
<% else %>
        <%= link_to "Login", login_path %><br />
        <a href = "/users/new">Not a user? sign up</a>
<% end %>

</div>
<%= yield %>


</body>

</html>

app/views/messages/_message.html.erb
<!--<meta http-equiv="refresh" content="15" />-->


<%= div_for message do %>

    <% id=message.sender_id %>
    <% if id!=nil then %>
    <% us=User.find_by_id(id)%>

     <%= us.email.to_s%>:  <%= message.message_text %>
<% end %>



  

<% end %>

app/views/messages/index.html.erb
<a href="/privateMessages">Private Messages</a>
<br>
<%= link_to 'Classroom', root_path %></td>

<!--
choosec date:
<select onChange="test();">
<option>today</option>
<option>1 week ago to date</option>
<option>whole messages</option>
</select>
-->
<%= form_for(@message) do |f| %>

  <div class="field">
    <%= f.label :message_text %><br />
   
    <%= f.text_field :message_text %>
  </div>
  <div class="field">
   <%@message.user_id=current_user.id%>
   <%@message.sender_id=current_user.id%>
   
   <%= f.hidden_field :user_id %>
   <%= f.hidden_field :sender_id %>

  </div>

  <div  class="actions">
<a name="bottom"></a>
    <%= f.submit 'send' %>
  </div>
<% end %>
<%session['saved_location']='Messages'%>

<table>
  <tr>
    <th>Global Messages:</th>
      
   
   <th></th>
    <th></th>
    <th></th>
  </tr>


  <tr>

<td>
<select name="drop1" id="Select1"  style = "width:=400px"   multiple="multiple">

<% @messages.each do |message| %>



    <% id=message.sender_id %>
    <% if id!=nil then %>
    <% us=User.find_by_id(id)%>

    <option value="<%= message.id %>"> <%= us.email.to_s%>:  <%= message.message_text %></option>

      
   
<%end%>
<% end %>


</select>  

</table>

app/views/messages/new.html.erb
<%= form_for([@user, @user.messages.new]) do |f| %>
  <div class="field">
    <%= f.label :message_text %><br />
    <%= f.text_field :message_text %>
  </div>
  <div class="field">
   
    <%= f.hidden_field :user_id %>
  </div>

  <div  class="actions">
<a name="bottom"></a>
    <%= f.submit 'send' %>
  </div>
<% end %>

app/views/messages/privateMessages.html.erb
<script type="text/javascript">
function showPopup(url,name) {

var e = document.getElementById("Select2");


var strVal = e.options[e.selectedIndex].value;


url=url+strVal;
newwindow=window.open(url,strVal,'height=220,width=520,top=200,left=300,resizable');
if (window.focus) {newwindow.focus()}
}
</script>


<a href="/messages">Global Messages</a>
<br>

<%= link_to 'Classroom', root_path %></td>

<br>
Please Double Click on each message to start chatting with the sender.
<table>
  <tr>
    <th>Private Messages:</th>
      
   
   <th></th>
    <th></th>
    <th></th>
  </tr>


  <tr>

<td>
<select name="drop2" id="Select2"  style = "width:=400px"   multiple="multiple" onDblClick="showPopup('/userMessage/',1);return(false);">

<% @private_messages.each do |pmessage| %>



    <% id=pmessage.sender_id %>
    <% if id!=nil then %>
    <% us=User.find_by_id(id)%>

    <option value="<%= pmessage.sender_id %>" > <%= us.email.to_s%>:  <%= pmessage.message_text %></option>

      
   
<%end%>
<% end %>


</select>  

</table>

app/views/messages/userMessage.html.erb
<meta http-equiv="refresh" content="10" />
<% us=User.find(params[:id])%>

<h4><font color='green'><%= us.first_name%> <%= us.last_name%></font></h4>

<%= form_for(@message) do |f| %>

  <div class="field">
    <%= f.label :message_text %><br />
   
    <%= f.text_field :message_text %>
  </div>
  <div class="field">
   <%@message.user_id=current_user.id%>
   <%@message.sender_id=current_user.id%>
   <%@message.receiver_id=params[:id]%>

   <%= f.hidden_field :user_id %>
   <%= f.hidden_field :sender_id %>
   <%= f.hidden_field :receiver_id %>
  </div>

  <div  class="actions">
<a name="bottom"></a>
    <%= f.submit 'send' %>
  </div>
<% end %>

<%session['saved_location']='userMessage'%>

<%session['userMessageParam']=params[:id]%>
<div id="messages">

 <%= render Message.where("(sender_id = :uid1 AND receiver_id= :uid2) OR (sender_id= :uid2 AND receiver_id= :uid1)", {:uid1=> current_user.id, :uid2 => params[:id]}) %>

</div>

app/views/spots/index.html.erb
<script type="text/javascript">

function showPopup(url,name) {
newwindow=window.open(url,name,'height=220,width=520,top=200,left=300,resizable');
if (window.focus) {newwindow.focus()}
}

</script>

<a href="/messages" > Global Messages</a>
<br>
<a href="/privateMessages" onClick="refreshParent();">Private Messages</a>
<br>
<br>
<h3>Click on each user to send a private message. </h3>
<div style="float:right ; border-style: solid; border-color: #000000; width: 80%; height:400px; margin-right:5%">
    <h3 Style="Margin-left:45%">Classroom</h3>
    <div style="border: thin solid #C0C0C0; margin: 5% 44% 5% 44%; height: 20px" id="professorplace">
    </div>
    <% count = 1 %>
    <% @spots.each do |spot| %>
    <% if ((count-1)/5)%2==0  %>
       <% if count%5== 0 %> 
           <% if spot.sessionid != nil %> 
	<a href="/userMessage/<%= spot.sessionid %>" onClick="showPopup(this.href,<%= spot.sessionid %>);return(false);" class="student"><%= User.find(spot.sessionid).first_name %></a>
           <% else %>
	<a href="/spots/<%= spot.id %>" class="student"> * </a>
            <% end %>
          </div>
       <% elsif count%5== 1 %>
           <div style="border: thin solid #C0C0C0; float:left; margin-left: 5%; margin-bottom: 1%;  width:40%">
           <% if spot.sessionid != nil %>
	<a href="/userMessage/<%= spot.sessionid %>" onClick="showPopup(this.href,<%= spot.sessionid %>);return(false);" class="student"><%= User.find(spot.sessionid).first_name %></a>
           <% else %>
	<a href="/spots/<%= spot.id %>" class="student"> * </a>
           <% end %>
      <% else %>
	<% if spot.sessionid != nil %>
		<a href="/userMessage/<%= spot.sessionid %>" onClick="showPopup(this.href,<%= spot.sessionid %>);return(false);" class="student"><%= User.find(spot.sessionid).first_name %></a>
       	<% else %>
		<a href="/spots/<%= spot.id %>" class="student"> * </a>
	<% end %>
      <% end %>
    <% else %>
       <% if count%5== 0 %> 
           <% if spot.sessionid != nil %>
           	<a href="/userMessage/<%= spot.sessionid %>" onClick="showPopup(this.href,<%= spot.sessionid %>);return(false);" class="student"><%= User.find(spot.sessionid).first_name %></a>
           <% else %>
	<a href="/spots/<%= spot.id %>" class="student"> * </a>
           <% end %>
           </div>
       <% elsif count%5== 1 %>
           <div style="border: thin solid #C0C0C0; float:right; margin-right: 5%; margin-bottom: 1%;  width:40%">
           <% if spot.sessionid != nil %>
	<a href="/userMessage/<%= spot.sessionid %>" onClick="showPopup(this.href,<%= spot.sessionid %>);return(false);" class="student"><%= User.find(spot.sessionid).first_name %></a>
           <% else %>
	<a href="/spots/<%= spot.id %>" class="student"> * </a>
           <% end %>
       <% else %>
           <% if spot.sessionid != nil %>
           	<a href="/userMessage/<%= spot.sessionid %>" onClick="showPopup(this.href,<%= spot.sessionid %>);return(false);" class="student"><%= User.find(spot.sessionid).first_name %></a>
           <% else %>
	<a href="/spots/<%= spot.id %>" class="student"> * </a>
           <% end %>
       <% end %>
    <% end %>
     <% count +=1 %>
    <% end %>
</div>
<br>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
<div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
<div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<%= div_for user do %>
  <%= user.first_name%> <%= user.last_name%>(<%= user.email %>)
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>


<table>

  <tr>

    <th>Username</th>

    <th>Password</th>

    <th>Name</th>

    <th>Lastname</th>

    <th></th>

    <th></th>

    <th></th>

  </tr>

<tr>
<td><%= current_user.email %></td>

    <td><%= current_user.password %></td>

    <td><%= current_user.first_name %></td>

    <td><%= current_user.last_name %></td>

    <td><%= link_to 'Show', current_user %></td>

    <td><%= link_to 'Edit', edit_user_path(current_user) %></td>

    <td><%= link_to 'Destroy', current_user, :confirm => 'Are you sure?', :method => :delete %></td>

  </tr>
</table>


<br />



<a href="/spots">Go back to classroom!</a>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h3> 
<font color="green">
<%= render @user %>
</font>
</h3>
<%= render :file => 'messages/new'%>

<div id="messages">
 <%= render @user.messages.where("(sender_id = :uid1 AND receiver_id= :uid2) OR (sender_id= :uid2 AND receiver_id= :uid1)", {:uid1=> current_user.id, :uid2 => @user.id}) %>

</div>